config/routes.rb
HackerBlues::Application.routes.draw do
  resources :comments

  resources :posts

  resources :comment_votes, :only => [:create, :destroy]

  resources :post_votes, :only => [:create, :destroy]

  resources :users

  match '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', :via => :delete

  root :to => 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :post
  belongs_to :author, :class_name => "User", :foreign_key => :user_id

  has_many :comment_votes
  has_many :voters, :through => :comment_votes
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  attr_accessible :comment_id, :vote, :user_id
  belongs_to :comment
  belongs_to :voter, class_name:'User', :foreign_key => :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url
  belongs_to :author, :class_name => "User", :foreign_key => :user_id

  has_many :comments
  has_many :post_votes
  has_many :voters, :through => :post_votes

end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  attr_accessible :vote, :post_id, :user_id
  belongs_to :post
  belongs_to :voter, class_name: "User", :foreign_key => :user_id
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password
  has_many :posts
  has_many :comments

  has_many :post_votes
  has_many :all_posts_by_voter, :through => :post_votes, :source => :voter
  has_many :comment_votes

  has_secure_password

  validates :email, :username, :password, :presence => true
  validates :email, :username, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

end

app/controllers/sessions_controller (Shereef Bishay's conflicted copy 2013-06-25).rb
class SessionsController < ApplicationController
 def new
 end

 def create
    if user = User.authenticate(params[:username], params[:password])
      session[:current_user_id] = user.id
      redirect_to :root
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end

end



.find_by_email(params[:email])

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
 end

 def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to :root
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new(params[:user])
  end

  def create
    new_user = User.new(params[:user])
    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to :root
    else
      redirect_to :new
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_id(session[:current_user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerBlues</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='header'>
    <div class='nav'>
      <%= link_to "Hacker Blues", :root %>
      <% if current_user %>
        You are <%= current_user.username %>
        <%= form_tag('/logout', method: "delete") do %>
          <%= submit_tag "Logout" %>
        <% end %>
      <% else %>
        <%= link_to "Login", login_path %>
        <%= link_to "Sign up", signup_path %>
      <% end %>
    </div>
  </div>

  <%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<li>
  <div class="first_line_all_posts">
    <span class="title">
      <%= link_to post.title, post.url %>
    </span> | <span id="user">
      <%= link_to post.author.username, post.author %>
    </span>
  </div>
  <div class="second_line_all_posts">
    <%= form_for post do |f| %>
      <%= hidden_field_tag(:vote, "1")  %>
      <%= hidden_field_tag(:post_id, post.id) %>
      <span class="upvote">
        <%= post.post_votes.sum('vote')%> votes
        <%= f.submit 'Up' %>
      </span>
      <span class="text" id="comment_count">
        <%= link_to post.comments.count, comment_path(post.id) %>comments
      </span>
    <% end %>
  </div>
</li>

app/views/posts/index.html.erb
<div class="all_container">
  <ul>
    <%= render @posts %>

  </ul>

</div>

app/views/users/new.html.erb
<div class="signup_container">
  <h1>Welcome</h1>

  <%= form_for @user, :html => { :class => "create_user" } do |f| %>
    <h1>Create User:</h1>
    <div>Username: <%= f.text_field :username %></div>
    <div>Email: <%= f.text_field :email %></div>
    <div>Password: <%= f.password_field :password %></div>
    <%= f.submit 'Create me!' %>
  <% end %>
</div>